<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUA4HNNWDH" ignored="2" name="Default test" tests="1" failures="1" timestamp="16 Apr 2018 21:08:47 GMT" time="35.829" errors="0">
  <testcase name="loginpageTitleTest" time="0.048" classname="com.hybridFramework.testcases.LoginTest">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;...icial Site | New $35[] TV Deal!&amp;gt; but was:&amp;lt;...icial Site | New $35[5] TV Deal!&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<...icial Site | New $35[] TV Deal!> but was:<...icial Site | New $35[5] TV Deal!>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hybridFramework.testcases.LoginTest.loginpageTitleTest(LoginTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginpageTitleTest -->
  <testcase name="validateLogoTest" time="0.0" classname="com.hybridFramework.testcases.LoginTest">
    <ignored/>
  </testcase> <!-- validateLogoTest -->
  <testcase name="logintest" time="0.0" classname="com.hybridFramework.testcases.LoginTest">
    <ignored/>
  </testcase> <!-- logintest -->
</testsuite> <!-- Default test -->
